const SCENE_CORNER_RADIUS = 20
const BORDER_WIDTH = 20
const MENU_WIDTH = 400

const SECTION_FONTSIZE = 
const CONTENT_FONTSIZE = 

const BACKGROUND_COLOR = 
const MENU_BACKGROUND_COLOR = 
const DISPLAY_BACKGROUND_COLOR = 

const SLIDER_LINE_WIDTH = 20
const SLIDER_COLOR_RIGHT = 
const SLIDER_COLOR_LEFT = 
const SLIDER_COLOR_CIRCLE = 

const MENU_COLOR_ACTIVE = 
const MENU_COLOR_HOVER = 
const MENU_COLOR_EVEN = 
const MENU_COLOR_ODD = 
const MENU_COLOR_INACTIVE = 

const BUTTON_WIDTH = 200
const BUTTON_COLOR_INACTIVE = 
const BUTTON_COLOR_ACTIVE = 
const BUTTON_COLOR_HOVER = 
