const SCENE_CORNER_RADIUS = 20
const BORDER_WIDTH = 20
const MENU_WIDTH = 400

const SECTION_FONTSIZE = 30
const CONTENT_FONTSIZE = 20

const BACKGROUND_COLOR = :white
const MENU_BACKGROUND_COLOR = :blue
const DISPLAY_BACKGROUND_COLOR = RGBf(0.9, 0.9, 0.9)

const SLIDER_LINE_WIDTH = 20
const SLIDER_COLOR_RIGHT = :red
const SLIDER_COLOR_LEFT = :green
const SLIDER_COLOR_CIRCLE = :blue

const MENU_COLOR_ACTIVE = :red
const MENU_COLOR_HOVER = :green
const MENU_COLOR_EVEN = :blue
const MENU_COLOR_ODD = :red
const MENU_COLOR_INACTIVE = :green

const BUTTON_WIDTH = 200
const BUTTON_COLOR_INACTIVE = :red
const BUTTON_COLOR_ACTIVE = :green
const BUTTON_COLOR_HOVER = :blue
