# Simulation settings
const TIME_STEP = 1E-8

const SPECIES_WEIGHTING = 1E21
const SPECIES_MASS = 6.63E-26
const SPECIES_REF_TEMPERATURE = 273
const SPECIES_REF_EXPONENT = 0.77
const SPECIES_REF_DIAMETER = 4.05E-10

# Mesh length
const MESH_NUM_CELLS = (120, 60)

# Size of preallocated vectors
const MAX_NUM_WALLS_PER_CELL = 1000
const MAX_NUM_PARTICLES_PER_CELL = 1000
const MAX_NUM_PARTICLES_PER_THREAD = 100000
# TODO MAX_NUM_PARTICLES_TO_PLOT!